/**
 * Created by 小剑 on 2017/2/20.
 */
var conDateJson = {
    conId1:[
        {
            imgSrc:'./images/conm/conm1-1.jpg',
            describe:'日本花王LAURIER F系列卫生巾瞬吸透气棉柔 日用22.5cm*22片/包*2（海外版）',
            price:'45',
            old_price:'84',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-2.jpg',
            describe:'【全面补充】美国Childlife三驾马车 钙镁锌+VC+23种维生素矿物质复合营养液（海外版）',
            price:'235',
            old_price:'509',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-3.jpg',
            describe:'韩国可莱丝Clinie针剂水库睡眠面膜 15ml/袋*10（海外版）',
            price:'75',
            old_price:'170',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-4.jpg',
            describe:'【提高睡眠质量】德国喜宝HIPP无糖苹果全麦晚安米粉高钙铁锌（8个月以上）500g/盒*2（海外版）',
            price:'122',
            old_price:'260',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-5.jpg',
            describe:'芭比Barbie洗发沐浴二合一550ml送杏仁嫩白沐浴乳300ml(特惠装)',
            price:'29',
            old_price:'46',
            red:'洗发沐浴一起搞定！'
        },
        {
            imgSrc:'./images/conm/conm1-6.jpg',
            describe:'【强力除菌易清洗】日本山本汉方贝壳粉90g（海外版）',
            price:'72',
            old_price:'101',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-7.jpg',
            describe:'【缓解牙龈出血】新西兰红印Red Seal天然蜂胶牙膏100g/支*1+柠檬牙膏100g/支*1（海外版）',
            price:'72',
            old_price:'95',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-8.jpg',
            describe:'好孩子饮水杯婴幼儿吸管杯宝宝训练杯儿童学饮杯防漏320ml',
            price:'36',
            old_price:'59',
            red:'【水量自控防呛防漏】'
        },
        {
            imgSrc:'./images/conm/conm1-9.jpg',
            describe:'好孩子餐椅儿童便携折叠餐椅宝宝可调节餐椅吃饭多功能婴儿餐椅',
            price:'183',
            old_price:'399',
            red:'【折叠可调节】'
        },
        {
            imgSrc:'./images/conm/conm1-10.jpg',
            describe:'【打开Ta的心锁】蒂凡尼Tiffany & Co. Heart key珐琅爱心钥匙项链 蓝色',
            price:'1988',
            old_price:'2599',
            red:'意大利直邮包邮包税'
        },
        {
            imgSrc:'./images/conm/conm1-11.jpg',
            describe:'柯克兰kirkland杏仁夹心牛奶巧克力豆 1.36kg',
            price:'247',
            old_price:'339',
            red:'美国直邮 包邮包税'
        },
        {
            imgSrc:'./images/conm/conm1-12.jpg',
            describe:'德国长发公主Rapunzel儿童蝴蝶结意面 意大利面  无蛋（12个月以上）500g（海外版）',
            price:'65',
            old_price:'102',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-13.jpg',
            describe:'日本象印ZOJIRUSHI不锈钢真空保温杯SM-JD48-PA粉色480ml',
            price:'266',
            old_price:'350',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-14.jpg',
            describe:'新西兰红印Red Seal天然蜂胶牙膏 牙龈出血 100g/支*2（海外版）',
            price:'79',
            old_price:'112',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-15.jpg',
            describe:'【滋润肌肤】韩国悦诗风吟Innisfree芦荟面膜  10片（海外版）',
            price:'72',
            old_price:'207',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-16.jpg',
            describe:'美国健安喜GNCCalcium Citrate 1000补钙柠檬酸钙片1000mg×180粒（海外版）',
            price:'95',
            old_price:'129',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-17.jpg',
            describe:'【发奶不发胖】德国喜宝HiPP Bio Stilltee有机催乳茶 30g/盒*2（海外版）',
            price:'85',
            old_price:'118',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-18.jpg',
            describe:'【水果谷物麦片】德国喜宝Hipp有机混合水果麦片（1岁以上）200g/盒*2（海外版）',
            price:'74',
            old_price:'98',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-19.jpg',
            describe:'日本花王LAURIER F系列卫生巾瞬吸透气棉柔 日用25cm*18片/包*2（海外版）',
            price:'74',
            old_price:'118',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-20.jpg',
            describe:'韩国可莱丝Clinie HDP 去黑头水洗面膜 15ml/袋*10（海外版）',
            price:'88',
            old_price:'120',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-21.jpg',
            describe:'【柔顺爽滑】爱茉莉Amore美仙精油护发油 70ml（海外版）',
            price:'61',
            old_price:'81',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-22.jpg',
            describe:'【营养丰富】德国喜宝Hipp饼干燕麦牛奶晚安米粉米糊（6个月以上）500g（海外版）',
            price:'65',
            old_price:'86',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-23.jpg',
            describe:'【舒缓滋润皮肤】美国加州宝宝CaliforniaBaby婴儿金盏花洗发沐浴露二合一251ml（海外版）',
            price:'95',
            old_price:'186',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-24.jpg',
            describe:'【保湿抗皱】Elizavecca Green Piggy小青猪胶原蛋白睡眠面膜 100g（海外版）',
            price:'69',
            old_price:'112',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-25.jpg',
            describe:'宝英宝Paw in Paw清爽型面霜  45ml（2017/5/23前可使用）',
            price:'29',
            old_price:'51',
            red:'滋养肌肤'
        },
        {
            imgSrc:'./images/conm/conm1-26.jpg',
            describe:'美国世界最好Earth'+"'"+'s Best有机豌豆糙米泥2段（6个月以上）113g（2017/5/20前可食用）（海外版）',
            price:'5',
            old_price:'38',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-27.jpg',
            describe:'新西兰汤普森Thompson'+"'"+'s超级卵磷脂200粒(海外版)（2017/5/1前可食用）	',
            price:'55',
            old_price:'232.7',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-28.jpg',
            describe:'【排毒润肠通便】澳洲乐康膏Nu-lax果蔬润肠膏通便排毒防便秘500g（2017/5/1前可食用）（海外版）',
            price:'25',
            old_price:'155',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-29.jpg',
            describe:'德国特福芬Topfer有机奶粉 1段（0-6个月）600g（2017/7/30前可食用）（海外版）',
            price:'59',
            old_price:'324',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-30.jpg',
            describe:'美国健安喜GNC儿童鱼油DHA软糖（2017/5/1前可食用）（海外版）',
            price:'59',
            old_price:'59',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-31.jpg',
            describe:'宝英宝Paw in Paw儿童温和柔嫩润肤露  100ml（2017/5/23前可使用）',
            price:'39',
            old_price:'69',
            red:'温和柔嫩'
        },
        {
            imgSrc:'./images/conm/conm1-32.jpg',
            describe:'美国健安喜GNC SUPER DIGESTIVE ENZYMES超级多维消化酶100粒（2017/5/1前可食用）（海外版）',
            price:'49',
            old_price:'155',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-33.jpg',
            describe:'【美容养身必备】美国健安喜女性维生素矿物质缓释片90粒（2017/6/1前可食用）（海外版）',
            price:'39',
            old_price:'181',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-34.jpg',
            describe:'美国嘉宝Gerber香蕉星星泡芙（8个月以上）42g（2017/6/16前可食用）（海外版）',
            price:'9',
            old_price:'56',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-35.jpg',
            describe:'英国爱他美美乐宝奶粉Aptamil 2段（6-12个月）900g（2017/6/29前可食用）（海外版）',
            price:'125',
            old_price:'319',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-36.jpg',
            describe:'【提高钙吸收率】金恩贝施橙味乳矿物盐凝胶糖果乳钙10粒（2017/6/5前可食用）',
            price:'15',
            old_price:'20',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-37.jpg',
            describe:'【舒缓敏感 补水保湿】美国艾维诺Aveeno天然燕麦舒缓润肤保湿乳霜140g（海外版）',
            price:'55',
            old_price:'106',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-38.jpg',
            describe:'美国Baby Bjorn宝宝软胶围嘴红色（海外版）',
            price:'106',
            old_price:'184',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-39.jpg',
            describe:'【入口即溶】美国嘉宝Gerber草莓苹果星星泡芙（8个月以上）42g/瓶*2（海外版）',
            price:'54',
            old_price:'96',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-40.jpg',
            describe:'【补充每日维C】美国Childlife维C营养液（6个月以上）118.5ml/瓶*2（海外版）',
            price:'99',
            old_price:'222',
            red:''
        }
    ],
    conId2:[
        {
            imgSrc:'./images/conm/conm2-1.jpg',
            describe:'日本和光堂Wakodo婴儿低敏润肤露150ml（海外版）',
            price:'65',
            old_price:'95',
            red:'滋润宝宝的肌肤！'
        },
        {
            imgSrc:'./images/conm/conm2-2.jpg',
            describe:'香港Bobo晶透学饮杯(180毫升)BB305D(不同颜色随机发货) ',
            price:'57',
            old_price:'110',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-3.jpg',
            describe:'美国布朗博士Dr. Brown'+"'"+'s Natural Flow海绵尼龙奶瓶刷（颜色随机）/个*2',
            price:'59',
            old_price:'88',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-4.jpg',
            describe:'【提高睡眠质量】德国喜宝HIPP无糖苹果全麦晚安米粉高钙铁锌（8个月以上）500g/盒*2（海外版）',
            price:'122',
            old_price:'260',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-5.jpg',
            describe:'【防水隔凉】贝博氏爬爬乐/森林双面经济爬行垫MB-R017A  200*180*0.5cm',
            price:'36',
            old_price:'47',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-6.jpg',
            describe:'【敏肌宝宝首选】德国喜宝Hipp有机免敏胡萝卜泥（4个月以上）125g/瓶*4（海外版）',
            price:'69',
            old_price:'144',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-7.jpg',
            describe:'【操作简单 激发兴趣】美国小泰克Little tikes敲击乐电子琴（颜色随机）',
            price:'165',
            old_price:'220',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-8.jpg',
            describe:'【肌肤透白无暇】兰蔻Lancome智能密钥臻白精华乳 10ml',
            price:'68',
            old_price:'90',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-9.jpg',
            describe:'【天然温和洁净】宝宝金水美嘟兔系列儿童倍护滋养洗手液（橄榄+芦荟） 480ml',
            price:'19',
            old_price:'29',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-10.jpg',
            describe:'【补铁易吸收】优朵Uoodo优铁多凝胶糖果0.88g*30粒',
            price:'68',
            old_price:'90',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-11.jpg',
            describe:'【缓解湿疹 一盒多用】德国贝娜婷Penaten万用膏 50ml（海外版）',
            price:'35',
            old_price:'46',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-12.jpg',
            describe:'韩国保宁B&B婴幼儿除菌纤维洗涤剂桶装1500ml+补充装1300ml',
            price:'119',
            old_price:'178',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-13.jpg',
            describe:'新西兰红印Red Seal小苏打美白去渍牙膏双重美白清洁100g*2（海外版）',
            price:'55',
            old_price:'110',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-14.jpg',
            describe:'澳洲斯维斯Swisse CHLOROPHYLL 液体叶绿素口服液（梅子味）500ml/瓶*2（海外版）',
            price:'159',
            old_price:'312',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-15.jpg',
            describe:'全棉时代Purcotton纯棉产妇一次性内裤独立包装5件/袋 M号',
            price:'42',
            old_price:'59',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-16.jpg',
            describe:'好孩子XPE婴儿爬行垫环保加厚宝宝爬爬垫儿童地垫泡沫垫游戏毯',
            price:'280',
            old_price:'639',
            red:'【环保无毒无味】'
        },
        {
            imgSrc:'./images/conm/conm2-17.jpg',
            describe:'【白色恋人白巧克力夹心饼干 27枚',
            price:'176',
            old_price:'233',
            red:'日本直邮 包税'
        },
        {
            imgSrc:'./images/conm/conm2-18.jpg',
            describe:'ThermaCare热敷贴带祛痛贴肩颈腕部镇痛贴9片装',
            price:'195',
            old_price:'258',
            red:'美国直邮 包邮包税'
        },
        {
            imgSrc:'./images/conm/conm2-19.jpg',
            describe:'好孩子电动吸奶器挤奶器吸乳器静音吸力大孕产妇涨奶自动按摩吸乳',
            price:'209',
            old_price:'399',
            red:'【吸乳按摩双频可调】'
        },
        {
            imgSrc:'./images/conm/conm2-20.jpg',
            describe:'【清肺健肺 对抗雾霾】新西兰好健康Goodhealth Healthy Lungs 肺康天然草本健肺液200ml（海外版）',
            price:'169',
            old_price:'246',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-21.jpg',
            describe:'德国喜宝Hipp有机苹果香蕉谷物泥（8个月以上）190g/瓶*4（海外版）',
            price:'102',
            old_price:'152',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-22.jpg',
            describe:'【防烫耐摔】欧米兰Omilan不锈钢宝宝餐具套装（勺叉餐具+双耳汤碗+多用碗+水杯）',
            price:'79',
            old_price:'138',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-23.jpg',
            describe:'【预防胸部下垂】美国Palmer'+"'"+'s胶原弹力紧致丰胸膏 125g（海外版）',
            price:'67',
            old_price:'88',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-24.jpg',
            describe:'天然世家宝宝一分钟小面片系列-四合一味( 桶装45g*5包)',
            price:'82',
            old_price:'132',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-25.jpg',
            describe:'新西兰Karicare奶粉金装加强免疫1段（0-6个月）900g（2017/7/14前可食用）（海外版）',
            price:'99',
            old_price:'298',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-26.jpg',
            describe:'美国嘉宝Gerber混合水果汁（4个月以上）118ml（2017/3/23前可食用）（海外版）',
            price:'6',
            old_price:'46',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-27.jpg',
            describe:'美国健安喜GNC Lycopene番茄红素30mg×60粒（2017/7/1前可食用）（海外版）',
            price:'69',
            old_price:'207',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-28.jpg',
            describe:'美国Martek婴幼儿life'+"'"+'s 海藻油DHA软胶囊 90粒（2017/4/1前可食用）（海外版）',
            price:'35',
            old_price:'298',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-29.jpg',
            describe:'德国贝娜婷Penaten婴儿抗敏润肤乳液 400ml（2017/5/1前可使用）（海外版）',
            price:'38',
            old_price:'51',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-30.jpg',
            describe:'法国菲利普维尚Philippe Vigean 橄榄油核桃油调和油500ml（2017/4/7前可食用）',
            price:'59',
            old_price:'207',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-31.jpg',
            describe:'德国凯莉泓乐德文版Holle 2段（6-10个月）600g（2017/3/28前可食用）（海外版）',
            price:'29',
            old_price:'259',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-32.jpg',
            describe:'美国Martek life'+"'"+'s DHA孕妇哺乳期海藻油 30粒+维生素叶酸 30粒（2017/5/1前可食用）（海外版）',
            price:'79',
            old_price:'231',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-33.jpg',
            describe:'荷兰牛栏Bambix精细谷物营养米粉（6个月以上）250g（2017/4/9前可食用）（海外版）',
            price:'22',
            old_price:'69',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-34.jpg',
            describe:'新西兰Karicare奶粉金装加强免疫2段（6-12个月）900g（2017/7/15前可食用）（海外版）',
            price:'89',
            old_price:'356',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-35.jpg',
            describe:'德国喜宝HIPP无糖苹果全麦晚安米粉高钙铁锌（8个月以上）500g（2017/3/31前可食用）',
            price:'12',
            old_price:'77',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-36.jpg',
            describe:'【延缓衰老 抗辐射】美国健安喜GNC 葡萄籽精华300mg×100粒（2017/3/1前可食用）（海外版）',
            price:'15',
            old_price:'311',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-37.jpg',
            describe:'德国特福芬Topfer有机奶粉 1段（0-6个月）600g（2017/7/30前可食用）（海外版）',
            price:'59.9',
            old_price:'324',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-38.jpg',
            describe:'方广有机三文鱼蔬菜营养米粉（6个月以上）180g（2017/3/23前可食用）',
            price:'29',
            old_price:'56',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-39.jpg',
            describe:'Swisse MEN'+"'"+'S老年男士50岁以上专用复合维生素90粒（2017/5/1前可食用）（海外版）',
            price:'139',
            old_price:'379',
            red:''
        },
        {
            imgSrc:'./images/conm/conm2-40.jpg',
            describe:'美国Martek life'+"'"+'s DHA孕妇哺乳期海藻油 30粒+维生素叶酸 30粒（2017/7/1前可食用）（海外版）',
            price:'99',
            old_price:'231',
            red:''
        }
    ],

    conId3:[
        {
            imgSrc:'./images/conm/conm1-21.jpg',
            describe:'【柔顺爽滑】爱茉莉Amore美仙精油护发油 70ml（海外版）',
            price:'61',
            old_price:'81',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-22.jpg',
            describe:'【营养丰富】德国喜宝Hipp饼干燕麦牛奶晚安米粉米糊（6个月以上）500g（海外版）',
            price:'65',
            old_price:'86',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-23.jpg',
            describe:'【舒缓滋润皮肤】美国加州宝宝CaliforniaBaby婴儿金盏花洗发沐浴露二合一251ml（海外版）',
            price:'95',
            old_price:'186',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-24.jpg',
            describe:'【保湿抗皱】Elizavecca Green Piggy小青猪胶原蛋白睡眠面膜 100g（海外版）',
            price:'69',
            old_price:'112',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-25.jpg',
            describe:'宝英宝Paw in Paw清爽型面霜  45ml（2017/5/23前可使用）',
            price:'29',
            old_price:'51',
            red:'滋养肌肤'
        },
        {
            imgSrc:'./images/conm/conm1-26.jpg',
            describe:'美国世界最好Earth'+"'"+'s Best有机豌豆糙米泥2段（6个月以上）113g（2017/5/20前可食用）（海外版）',
            price:'5',
            old_price:'38',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-27.jpg',
            describe:'新西兰汤普森Thompson'+"'"+'s超级卵磷脂200粒(海外版)（2017/5/1前可食用）	',
            price:'55',
            old_price:'232.7',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-28.jpg',
            describe:'【排毒润肠通便】澳洲乐康膏Nu-lax果蔬润肠膏通便排毒防便秘500g（2017/5/1前可食用）（海外版）',
            price:'25',
            old_price:'155',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-29.jpg',
            describe:'德国特福芬Topfer有机奶粉 1段（0-6个月）600g（2017/7/30前可食用）（海外版）',
            price:'59',
            old_price:'324',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-30.jpg',
            describe:'美国健安喜GNC儿童鱼油DHA软糖（2017/5/1前可食用）（海外版）',
            price:'59',
            old_price:'59',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-29.jpg',
            describe:'德国特福芬Topfer有机奶粉 1段（0-6个月）600g（2017/7/30前可食用）（海外版）',
            price:'59',
            old_price:'324',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-30.jpg',
            describe:'美国健安喜GNC儿童鱼油DHA软糖（2017/5/1前可食用）（海外版）',
            price:'59',
            old_price:'59',
            red:''
        }
    ],
    conId4:[
        {
            imgSrc:'./images/conm/conm1-1.jpg',
            describe:'日本花王LAURIER F系列卫生巾瞬吸透气棉柔 日用22.5cm*22片/包*2（海外版）',
            price:'45',
            old_price:'84',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-2.jpg',
            describe:'【全面补充】美国Childlife三驾马车 钙镁锌+VC+23种维生素矿物质复合营养液（海外版）',
            price:'235',
            old_price:'509',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-3.jpg',
            describe:'韩国可莱丝Clinie针剂水库睡眠面膜 15ml/袋*10（海外版）',
            price:'75',
            old_price:'170',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-4.jpg',
            describe:'【提高睡眠质量】德国喜宝HIPP无糖苹果全麦晚安米粉高钙铁锌（8个月以上）500g/盒*2（海外版）',
            price:'122',
            old_price:'260',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-5.jpg',
            describe:'芭比Barbie洗发沐浴二合一550ml送杏仁嫩白沐浴乳300ml(特惠装)',
            price:'29',
            old_price:'46',
            red:'洗发沐浴一起搞定！'
        },
        {
            imgSrc:'./images/conm/conm1-6.jpg',
            describe:'【强力除菌易清洗】日本山本汉方贝壳粉90g（海外版）',
            price:'72',
            old_price:'101',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-7.jpg',
            describe:'【缓解牙龈出血】新西兰红印Red Seal天然蜂胶牙膏100g/支*1+柠檬牙膏100g/支*1（海外版）',
            price:'72',
            old_price:'95',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-8.jpg',
            describe:'好孩子饮水杯婴幼儿吸管杯宝宝训练杯儿童学饮杯防漏320ml',
            price:'36',
            old_price:'59',
            red:'【水量自控防呛防漏】'
        },
        {
            imgSrc:'./images/conm/conm1-9.jpg',
            describe:'好孩子餐椅儿童便携折叠餐椅宝宝可调节餐椅吃饭多功能婴儿餐椅',
            price:'183',
            old_price:'399',
            red:'【折叠可调节】'
        },
        {
            imgSrc:'./images/conm/conm1-10.jpg',
            describe:'【打开Ta的心锁】蒂凡尼Tiffany & Co. Heart key珐琅爱心钥匙项链 蓝色',
            price:'1988',
            old_price:'2599',
            red:'意大利直邮包邮包税'
        },
        {
            imgSrc:'./images/conm/conm1-29.jpg',
            describe:'德国特福芬Topfer有机奶粉 1段（0-6个月）600g（2017/7/30前可食用）（海外版）',
            price:'59',
            old_price:'324',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-30.jpg',
            describe:'美国健安喜GNC儿童鱼油DHA软糖（2017/5/1前可食用）（海外版）',
            price:'59',
            old_price:'59',
            red:''
        }
    ],
    conId5:[
        {
            imgSrc:'./images/conm/conm1-11.jpg',
            describe:'柯克兰kirkland杏仁夹心牛奶巧克力豆 1.36kg',
            price:'247',
            old_price:'339',
            red:'美国直邮 包邮包税'
        },
        {
            imgSrc:'./images/conm/conm1-12.jpg',
            describe:'德国长发公主Rapunzel儿童蝴蝶结意面 意大利面  无蛋（12个月以上）500g（海外版）',
            price:'65',
            old_price:'102',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-13.jpg',
            describe:'日本象印ZOJIRUSHI不锈钢真空保温杯SM-JD48-PA粉色480ml',
            price:'266',
            old_price:'350',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-14.jpg',
            describe:'新西兰红印Red Seal天然蜂胶牙膏 牙龈出血 100g/支*2（海外版）',
            price:'79',
            old_price:'112',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-15.jpg',
            describe:'【滋润肌肤】韩国悦诗风吟Innisfree芦荟面膜  10片（海外版）',
            price:'72',
            old_price:'207',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-16.jpg',
            describe:'美国健安喜GNCCalcium Citrate 1000补钙柠檬酸钙片1000mg×180粒（海外版）',
            price:'95',
            old_price:'129',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-17.jpg',
            describe:'【发奶不发胖】德国喜宝HiPP Bio Stilltee有机催乳茶 30g/盒*2（海外版）',
            price:'85',
            old_price:'118',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-18.jpg',
            describe:'【水果谷物麦片】德国喜宝Hipp有机混合水果麦片（1岁以上）200g/盒*2（海外版）',
            price:'74',
            old_price:'98',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-19.jpg',
            describe:'日本花王LAURIER F系列卫生巾瞬吸透气棉柔 日用25cm*18片/包*2（海外版）',
            price:'74',
            old_price:'118',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-20.jpg',
            describe:'韩国可莱丝Clinie HDP 去黑头水洗面膜 15ml/袋*10（海外版）',
            price:'88',
            old_price:'120',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-14.jpg',
            describe:'新西兰红印Red Seal天然蜂胶牙膏 牙龈出血 100g/支*2（海外版）',
            price:'79',
            old_price:'112',
            red:''
        },
        {
            imgSrc:'./images/conm/conm1-15.jpg',
            describe:'【滋润肌肤】韩国悦诗风吟Innisfree芦荟面膜  10片（海外版）',
            price:'72',
            old_price:'207',
            red:''
        }
    ]
};

var menuDate = {
    list1:[
        {
            strong:'热门品牌',
            aLists:[
                '荷兰牛栏Nutrilon',
                '德国爱他美Aptamil',
                '德国喜宝Hipp',
                '荷兰美素Hero Baby',
                '英国牛栏Cow＆Gate',
                '新西兰爱他美Aptamil',
                '德国特福芬Topfer',
                '英国爱他美Aptamil',
                '新西兰Karicare',
                '澳洲a2',
                '德国凯莉泓乐Holle',
                '日本明治',
                '英国Nannycare',
                "澳洲贝拉米Bellamy's",
                '英国纽康特Neocate',
                '卡洛塔妮Karihome',
                '美国美赞臣Meadjohnson',
                '美国雅培Similac',
                '日本固力果',
                '新西兰惠氏Wyeth'
            ]
        },
        {
            strong:'优惠套餐',
            aLists:[
                '买7送1',
                '4罐优惠',
                '2罐优惠'
            ]
        },
        {
            strong:'优惠套餐',
            aLists:[
                '0-6个月',
                '6-12个月',
                '1-2岁',
                '2-3岁',
                '3-6岁',
                '儿童奶粉',
                '儿童奶粉（直邮）'
            ]
        },
        {
            strong:'奶粉分类',
            aLists:[
                '牛奶粉',
                '羊奶粉',
                '有机奶粉',
                '益生菌奶粉',
                '牛乳蛋白过敏奶粉',
                '乳糖不耐受奶粉',
                '早产儿奶粉',
                '孕妇奶粉',
                '宝宝奶粉（直邮）'
            ]
        }
    ],
    list2:[
        {
            strong:'热门品牌',
            aLists:[
                '德国喜宝Hipp',
                '美国嘉宝Gerber',
                "美国世界最好Earth's Best",
                '美国禧贝Happybaby',
                '德国长发公主Rapunzel',
                '意大利美林Mellin',
                '日本和光堂Wakodo',
                '日本贝亲Pigeon',
                '美国Yummy Earth',
                '亨氏Heinz',
                '韩国海地村',
                '美国优格曼Dremz',
                '美国谷百Plum',
                '伊威Eastwes',
                '荷兰牛栏',
                '方广',
                '德国贝唯他Bebivita',
                '韩国宝宝福德Baby food',
                '韩国宝噜噜 ',
                '意大利黛乐Dalla Costa'
            ]
        },
        {
            strong:'辅食分类',
            aLists:[
                '米粉/麦粉/粥',
                '肉泥/果泥/菜泥',
                '饮料/果汁',
                '调味/拌饭/油',
                '鱼肠/肉肠',
                '面条类',
                '宝宝零食',
                '宝宝辅食（直邮）'
            ]
        },
        {
            strong:'月龄',
            aLists:[
                '辅食添加初期',
                '4-6月',
                '7-9月',
                '10-12月',
                '12至36个月',
                '4至36个月',
                '6至36个月'
            ]
        },
        {
            strong:'优惠套餐',
            aLists:[
                '2瓶优惠',
                '4盒优惠'
            ]
        }
    ],
    list3:[
        {
            strong:'宝宝营养热门品牌',
            aLists:[
                '美国Childlife',
                '澳洲Bio Island',
                '美国康萃乐Culturelle',
                '加拿大Ddrops',
                '挪威小鱼Nordic naturals',
                '美国安利Amway',
                "美国熊宝宝l'il Critters"
            ]
        },
        {
            strong:'功效',
            aLists:[
                'DHA/鱼油',
                ' 钙镁锌铁',
                ' 维生素/VD',
                '益生菌',
                '补脑益智',
                '提高免疫力',
                "调节肠胃",
                '清火降火'
            ]
        },
        {
            strong:'营养人群',
            aLists:[
                '父母健康',
                '男士保健',
                '魅力女士',
                '青少年营养',
                '孕妈营养',
                '宝宝营养',
                "宝宝营养（直邮）",
                '成人保健品（直邮）'
            ]
        },
        {
            strong:'成人营养热门品牌',
            aLists:[
                '澳洲Swisse',
                '新西兰好健康Goodhealth',
                '美国康宝莱Herbalife',
                '澳洲澳佳宝Blackmores',
                '澳洲Healthy Care',
                '德国铁元',
                "日本宝丽POLA",
                '美国安利Amway'
            ]
        },
        {
            strong:'功效',
            aLists:[
                '美容养颜',
                '瘦身排毒',
                '提高免疫力',
                '补脑益智',
                '调节内分泌',
                '调节三高',
                "眼疲劳/明目",
                '胃肠调节',
                '改善睡眠',
                '改善贫血'
            ]
        }
    ],
    list4:[
        {
            strong:'热门品牌',
            aLists:[
                '日本花王Merries',
                '日本尤妮佳Moony',
                '日本大王GOO.N',
                '日本帮宝适',
                '美国小蜜蜂',
                '美国加州宝宝CaliforniaBaby',
                '美国艾维诺Aveeno',
                '日本贝亲Pigeon',
                '德国博朗',
                '德国NUK',
                '美国布朗博士',
                '日本贝塔Betta',
                '美国可么多么'
            ]
        },
        {
            strong:'纸尿裤/湿巾',
            aLists:[
                '纸尿裤',
                '拉拉裤',
                '湿巾',
                ' NB号',
                ' S号',
                ' M号',
                " L号",
                ' XL/XXL号'
            ]
        },
        {
            strong:'喂养用品',
            aLists:[
                '奶瓶/奶嘴',
                '水杯/水壶',
                '牙胶/安抚',
                '儿童餐具',
                '消毒/暖奶/调奶',
                '围兜/防溅衣',
                "辅食料理机",
                '奶瓶清洁/配件',
                '宝宝用品（直邮）'
            ]
        },
        {
            strong:'洗护/护理',
            aLists:[
                ' 防蚊驱蚊',
                '沐浴护肤',
                ' 护肤系列',
                '护臀系列',
                '牙刷/牙膏',
                '洗浴用具',
                "坐便器",
                ' 理发器',
                ' 医护用品',
                '防护用品',
                '指甲钳',
                '洗手液',
                '洗衣液/皂 ',
                '奶瓶/果蔬清洗液'
            ]
        },
        {
            strong:'车床座椅/日常用品',
            aLists:[
                '安全座椅',
                '手推车',
                '婴儿床/童床',
                ' 餐椅 ',
                '儿童行李箱'
            ]
        }
    ],
    list5:[
        {
            strong:'热门品牌',
            aLists:[
                '麦菲熊',
                'BabyBanz',
                '马克珍妮',
                '盈泰',
                '妙菲登',
                'lambkin kids ',
                '意婴堡',
                '怡妍宝贝',
                '麦西西',
                '花笙糖',
                '海绵泡泡',
                '欢乐熊Huanlexiong',
                '娃娃舒',
                '班杰威尔'
            ]
        },
        {
            strong:'婴幼服饰',
            aLists:[
                '新生儿礼盒',
                '连体服/哈衣',
                '婴幼内衣裤',
                ' 婴幼外出服',
                ' 口水巾/汗巾',
                ' 隔尿垫/尿布',
                " 围兜/肚围"
            ]
        },
        {
            strong:'童装',
            aLists:[
                'T恤/衬衫',
                '裤子',
                '裙子',
                '亲子装',
                '毛衣/针织衫',
                '卫衣/外套',
                "套装",
                '内衣家居服',
                '马甲/背心',
                '棉服/羽绒服',
                '宝宝服饰（直邮）'
            ]
        },
        {
            strong:'童鞋',
            aLists:[
                ' 学步/机能鞋',
                '短靴/雪地靴',
                ' 皮鞋/公主鞋',
                '运动/休闲鞋'
            ]
        },
        {
            strong:'寝居配饰',
            aLists:[
                '婴儿枕',
                '睡袋',
                '毛毯被褥',
                ' 床上用品 ',
                '浴巾毛巾',
                '新生儿手脚套',
                '帽子手套',
                '宝宝口罩',
                '袜子'
            ]
        }
    ],
    list6:[
        {
            strong:'热门品牌',
            aLists:[
                '德国Hape',
                '乐高LEGO',
                '美国费雪Fisherprice',
                '英国jellycat',
                '奥迪双钻',
                '优贝比Yobee',
                '贝博氏',
                '迪士尼',
                '美国小泰克Little tikes'
            ]
        },
        {
            strong:'积木/绘画/DIY',
            aLists:[
                '积木/拼插',
                '磁力片',
                '婴幼内衣裤',
                '拼图',
                '彩泥/绘画',
                '情景玩具'
            ]
        },
        {
            strong:'爬行健身/毛绒公仔',
            aLists:[
                '爬行垫/毯',
                '沙滩/戏水',
                '户外玩具',
                '滑板车/轮滑',
                '芭比娃娃',
                '卡通娃娃',
                "毛绒玩具",
                '抱枕/靠垫'
            ]
        },
        {
            strong:'动漫/卡通玩具',
            aLists:[
                '疯狂动物城',
                '变形金刚',
                '超级飞侠',
                '飓风战魂/陀螺',
                '海底小纵队',
                '巨神战击队',
                '巴拉拉小魔仙',
                '铠甲勇士',
                '机甲兽神/爆裂飞车',
                '奇积乐园',
                '魔幻车神',
                '其他卡通'
            ]
        },
        {
            strong:'乐器玩具',
            aLists:[
                '钢琴/电子琴',
                '吉他/贝斯',
                '其他乐器'
            ]
        },
        {
            strong:'书籍文具',
            aLists:[
                '绘本',
                '百科探索',
                '儿童文学',
                '有声读物'
            ]
        }
    ],
    list7:[
        {
            strong:'热门品牌',
            aLists:[
                '安满Anmum',
                '百洛Bio-Oil',
                "美国palmer's",
                '日本三洋DACCO',
                '德国舒氏Snug',
                '神豆Simdoo',
                '美国Lansinoh',
                '瑞士美德乐Medela',
                '德国喜宝Hipp',
                '碧缇丝'
            ]
        },
        {
            strong:'孕妈营养',
            aLists:[
                '孕妇奶粉',
                ' DHA/叶酸/备孕',
                ' 孕期营养',
                ' 产后调理',
                '催奶茶/绘画'
            ]
        },
        {
            strong:'孕妈护肤',
            aLists:[
                '面部护理',
                ' 妊娠纹/去疤',
                '身体护理',
                '乳房护理',
                '口腔护理',
                '洗发护发'
            ]
        },
        {
            strong:'孕妇穿着',
            aLists:[
                '防辐射服',
                '哺乳文胸',
                '长裤/托腹裤',
                '孕妇装',
                '孕妇内裤'
            ]
        },
        {
            strong:'产前产后',
            aLists:[
                '防溢乳垫',
                ' 吸奶器',
                ' 母乳储存',
                '  护腰枕',
                '  待产包',
                ' 塑身/束腹带 ',
                ' 托腹带',
                ' 产妇卫生巾',
                ' 产妇垫',
                ' 妈咪包',
                '背婴带',
                '胎心仪',
                '孕产用品（直邮）'
            ]
        },
        {
            strong:'书籍文具',
            aLists:[
                '绘本',
                '百科探索',
                '儿童文学',
                '有声读物'
            ]
        }
    ],
    list8:[
        {
            strong:'热门品牌',
            aLists:[
                '兰蔻Lancome',
                '韩国SNP',
                '韩国可莱丝Clinie',
                '九朵云Cloud 9',
                '资生堂Shiseido',
                '蓝蜥蜴BLUE LIZARD',
                '兰芝Laneige',
                '雅诗兰黛Estée Lauder',
                '倩碧Clinique',
                '韩国爱茉莉Amore',
                '日本花王Laurier'
            ]
        },
        {
            strong:'面部护肤',
            aLists:[
                '卸妆',
                '洁面',
                '化妆/爽肤水',
                '面霜/乳液',
                '精华',
                '眼部护理',
                '防晒/隔离',
                '面膜',
                '护肤套装',
                '剃须',
                '美妆个护（直邮）'
            ]
        },
        {
            strong:'香水彩妆',
            aLists:[
                '粉底/BB霜/遮瑕',
                '眉笔/眉粉',
                '睫毛膏',
                '眼线/眼影',
                '唇膏/唇彩',
                '腮红',
                "美妆工具",
                '女士香水',
                '男士香水'
            ]
        },
        {
            strong:'洗发护发/身体护肤/口腔护理',
            aLists:[
                '洗发护发',
                '直发器/卷发器/电吹风',
                '身体乳/沐浴露',
                '美体塑身',
                '颈部护理',
                '手足护理',
                '美胸丰胸',
                '牙膏/牙刷',
                '漱口水'
            ]
        },
        {
            strong:'女性护理',
            aLists:[
                '卫生巾/护垫',
                '私密护理',
                '脱毛膏'
            ]
        }
    ],
    list9:[
        {
            strong:'热门品牌',
            aLists:[
                '澳洲德运devondale',
                '安佳',
                '德国碧然德Brita',
                '泉林本色',
                '北欧欧慕Nathome',
                '惠人Hurom',
                '贝博氏',
                '迪士尼',
                '美国小泰克Little tikes'
            ]
        },
        {
            strong:'成人奶粉/食品饮料',
            aLists:[
                '全脂奶粉',
                ' 脱脂奶粉',
                ' 高钙奶粉',
                ' 羊奶粉',
                '休闲食品',
                '坚果/果仁',
                '蜂蜜',
                '冲调饮品',
                '酸奶/冰淇淋',
                '成人奶粉（直邮）',
                '食品饮料（直邮）'
            ]
        },
        {
            strong:'生活日用/居家/布艺',
            aLists:[
                '安全检测',
                '家居收纳',
                '净化除味',
                '口罩',
                "家庭清洁",
                "衣架/晾晒",
                "雨伞/雨具",
                "水杯/水壶",
                "内衣/睡衣",
                "毛巾浴巾",
                "床上用品",
                "居家用品（直邮）",
                "轻奢生活（直邮）"
            ]
        },
        {
            strong:'个护健康',
            aLists:[
                '按摩器/瘦腿仪',
                '体重秤/血压计',
                '足浴器/浴桶',
                '磨毛器/粘毛器'
            ]
        },
        {
            strong:'麦乐购礼品卡',
            aLists:[
                '500元',
                '1000元',
                '2000元',
                '5000元',
                '10000元'
            ]
        }
    ]
};